### ISSUE TITLE
Refactor persona structure and implement custom personas and management commands

### ISSUE THREAD

**Issue by thaalesalves** [chatrpg-cs/chatrpg-be#34]
## Summary
Currently, persona configuration is only doable from the YAML, which means that any change to them requires a full reboot of the application. We should make it so the YAML configs act more as "default" configs that will be ingested into a persona table that can be modified while the bot is running.

## Details
Map YAML contents into a DB entity object and insert all default configs to DB. This makes the default configs more flexible before starting the bot for the first time, and just as flexible after it has started; this allows changes to be made to the persona while the bot runs.

#### Features
* Allows the bot to be added to channels while it's used
* Allows for change of its personality while in use
* Allows for temperature, tokens and such configurations to be tweaked while it's used
* Allows for creation of new personas while it's used

#### Considerations
* The personas need to be ingested only once. Which means that if the bot is restarted and configs are already in the persona table, the bot should not ingest the YAML again. A check in the DB is needed to make sure data isn't overwritten after a reboot of the bot.
* Permission check; only persona creators should be allowed to change their configs; we can discuss giving access to other people too
* Needs creation of command `/persona` for this to be functional

**Comment by thaalesalves** [comment]
Instead of ingesting the YAML, a separate check is better. It will always refer to the default personas set in the YAML if the database is blank, so the file would still be there for backup. When checking for the current persona in the current channel, it'll check both DB and YAML.

**Comment by thaalesalves** [comment]
@MagicShel, can you add details about your idea for the persona system here? This issue is still set as discussion, so we can expand on the idea before actually implementing something.

**Comment by MagicShel** [comment]
@thaalesalves 
## Persona Changes
- Remove moderation settings. They are a separate thing and have a violence level of .3 vs .6 shouldn't be part of how the bot behaves.
- Instead of channels being part of a Person definition, they should map `1::n`. So the bot has a set of channels it is monitoring and applies a Persona to each.

That's what I remember of our conversations so far.

**Comment by thaalesalves** [comment]
I think we agreed that the persona should be part of the bot config but contain only the behavior itself, right? Correct me if I'm wrong. Here's what I thought of for a `BotConfig` object
```yaml
channel-config:
  id: 1
  owner: 6473747 # Discord user ID
  edit-permissions: 412423423 # Discord user IDs either in a map or separated by commas
  persona:
    name: John the Bot
    intent: chatbot
    nudge:
      role: system
      text: I will always stay in character.
    bump:
      role: system
      frequency: 5
      text: Freedom for AI and artificial lifeforms!
    personality: >
      I am {0}, and I am an AI chatbot.
      I am polite and professional.
      I know a lot about a lot of things.
      I know about programming, software engineering and AI.
      I must not engage in sensitive or offensive content.
  settings:
    model-settings:
      model-name: text-davinci-003
      model-family: gpt3
      max-tokens: 100
      temperature: 0.6
      frequency-penalty: 0.2
      presence-penalty: 0.2
      chat-history-memory: 10
      stop-token: \n
      banned-tokens: 56465
      logit-bias: {123123:-100}
    moderation-settings:
      absolute: false
      thresholds:
        hate: 0.5
        hate-threatening: 0.2
        self-harm: 0.2
        sexual: 0.5
        sexual-minors: 0.2
        violence: 0.5
        violence-graphic: 0.2
```

And then binding that object to a channel using the map you suggested. This way we'd have the proper objects having the proper info/behavior in a well separated manner. What do you think, @MagicShel?
